### ISSUE TITLE
Sync with PCem v10.1

### ISSUE THREAD

**Issue by DerekTurtleRoe** [OBattler/PCem-X#35]
It would be nice to make sure that all the features, fixes, and improvements were carried over.

I'm not sure if you guys have had any of the issues fixed in 10.1 on PCem-X, but even if you haven't, a sync would be nice. :smile: 

Also, you may want to check PR #33 as it contains some additional features and stuff I find interesting. :smile:

**Comment by bachimusprime** [comment]
I'll have you know that that PR causes regressions! One, nVidia VESA black screens. Two, RAM reporting is wrong.

**Comment by DerekTurtleRoe** [comment]
I suppose you would know best, since you made it. :smile: 

Are you planning on updating it? I was interested in the Riva stuff.

**Comment by timofonic** [comment]
There@OBattler's [PCem-X](https://github.com/OBattler/PCem-X). And Tom fork, I hope they merge someday. I wonder why are there three versions and no merge (okay, @MoochMcGee's [PCem-mooch](https://github.com/MoochMcGee/PCem-mooch) gets merged eventually).

Even better: Can it be merged into DOSBox?

There is @joncampbell123's [DosBox-X](https://github.com/joncampbell123/dosbox-x/) too. I see the -X suffix is becoming popular :D

And even more crazier: Why can't both be merged into QEMU and the emulators would be a custom build+GUI?

This code is used by QEMU and still actively maintained (google guys too, I wonder why)

https://github.com/dgibson/dtc/tree/master/libfdt
https://git.kernel.org/cgit/utils/dtc/dtc.git/tree/libfdt

**Comment by bachimusprime** [comment]
No, PCem, DOSBox, and QEMU are entirely different codebases. You can't just merge code willy nilly! Also, PCem-mooch is a divergent fork. I do not plan to contribute to upstream.

**Comment by DerekTurtleRoe** [comment]
@timofonic Heh, I wish we could just merge things like that and just have it magically work better. Unfortunately, that isn't how it works.

Besides, QEMU is way larger in scope than DOSBox or PCem.

@MoochMcGee Didn't know about your fork, will check it out!

**Comment by DerekTurtleRoe** [comment]
I think I will close this since 86Box is going to replace this, and also much of the changes since version 10.1 and 11 are going into that anyway.

**Comment by OBattler** [comment]
PCem-X has been officially superseded by 86Box.

**Comment by DerekTurtleRoe** [comment]
@OBattler I know, that's why I closed it. 😄
